name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev libxml2 libxml2-dev
          cd /usr/include && sudo ln -s x86_64-linux-gnu/curl
      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl
      - name: Build PHP extension
        run: |
          phpize
          ./configure
          make
      - name: Run tests
        run: make test
    services:
      solr:
        image: ingimarsson/pecl-solr
        ports:
          - 8983:8983
